require "manageiq/loggers/base"
require "manageiq/loggers/cloud_watch"
require "manageiq/loggers/container"
require "manageiq/loggers/journald"
require "manageiq/loggers/log_device"
require "manageiq/loggers/version"
